# Generated by Django 5.2.6 on 2025-11-29 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0002_alter_editor_publisher_alter_journalist_publisher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editor',
            options={'permissions': [('can_update', 'Can update posts'), ('can_remove', 'Can delete posts'), ('join_publsiher', 'Can join publisher'), ('can_view', 'Can view own articles')]},
        ),
        migrations.AlterModelOptions(
            name='journalist',
            options={'permissions': [('can_update', 'Can update posts'), ('can_create', 'Can write articles and newsletters'), ('can_remove', 'Can delete posts'), ('join_publsiher', 'Can join publisher'), ('can_view', 'Can view own articles')]},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'permissions': [('can_publish', 'Can publish posts')]},
        ),
        migrations.AlterModelOptions(
            name='reader',
            options={'permissions': [('can_subscribe', 'Can subscribe to journalist or publisher')]},
        ),
    ]
