# Generated by Django 5.2.8 on 2025-12-01 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_alter_editor_options_alter_journalist_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editor',
            options={'permissions': [('can_update', 'Can update posts'), ('can_remove', 'Can delete posts'), ('join_publsiher', 'Can join publisher'), ('can_view', 'Can view own articles'), ('can_publish', 'Can publish posts')]},
        ),
        migrations.AlterModelOptions(
            name='publisher',
            options={'permissions': [('can_publish', 'Can publish posts'), ('can_view', 'Can view own articles')]},
        ),
    ]
